name: Deploy Storybook to host

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: "Git commit tag"
        required: true
        type: string
        
  workflow_call:
    inputs:
      git-tag:
        description: "Git commit tag"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.git-tag}}
          fetch-depth: 0

      - run: npm ci

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
